{{- if .Values.calendarFrontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redwood-calendar.fullname" . }}-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "redwood-calendar.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.calendarFrontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "redwood-calendar.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "redwood-calendar.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: calendar-frontend
        image: "{{ .Values.global.imageRegistry }}{{ .Values.calendarFrontend.image.repository }}:{{ .Values.calendarFrontend.image.tag }}"
        imagePullPolicy: {{ .Values.calendarFrontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.calendarFrontend.service.targetPort }}
          name: http
        envFrom:
        - configMapRef:
            name: {{ include "redwood-calendar.fullname" . }}-frontend-config
        resources:
          {{- toYaml .Values.calendarFrontend.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}