{{- if .Values.calendarMcpServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redwood-calendar.fullname" . }}-mcp-server
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "redwood-calendar.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
spec:
  replicas: {{ .Values.calendarMcpServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "redwood-calendar.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mcp-server
  template:
    metadata:
      labels:
        {{- include "redwood-calendar.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mcp-server
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: mcp-server
        image: "{{ .Values.global.imageRegistry }}{{ .Values.calendarMcpServer.image.repository }}:{{ .Values.calendarMcpServer.image.tag }}"
        imagePullPolicy: {{ .Values.calendarMcpServer.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.calendarMcpServer.service.targetPort }}
          name: health
        envFrom:
        - configMapRef:
            name: {{ include "redwood-calendar.fullname" . }}-mcp-server-config
        resources:
          {{- toYaml .Values.calendarMcpServer.resources | nindent 12 }}
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}