apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-mcp-server
  namespace: redwood-university
  labels:
    app: calendar-mcp-server
    component: mcp-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calendar-mcp-server
  template:
    metadata:
      labels:
        app: calendar-mcp-server
        component: mcp-server
    spec:
      containers:
      - name: mcp-server
        image: calendar-mcp-server:latest
        ports:
        - containerPort: 8080
          name: health
        envFrom:
        - configMapRef:
            name: calendar-mcp-server-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-mcp-server
  namespace: redwood-university
  labels:
    app: calendar-mcp-server
    component: mcp-server
spec:
  selector:
    app: calendar-mcp-server
  ports:
  - port: 8080
    targetPort: 8080
    name: health
  type: ClusterIP